/* ============================================
   GlassCart — Product Data Store
   ============================================ */

const products = [
    {
        id: 1,
        name: "Wireless ANC Headphones Pro",
        category: "electronics",
        categoryLabel: "Electronics",
        price: 89.99,
        originalPrice: 129.99,
        rating: 4.8,
        reviews: 234,
        description: "Premium wireless headphones with Active Noise Cancellation, 40-hour battery life, and crystal-clear audio. Features Bluetooth 5.3 and multipoint connection.",
        badge: "Hot",
        colors: ["#2d3436", "#dfe6e9", "#2563EB"],
        sizes: null,
        inStock: true,
        features: ["Active Noise Cancellation", "40hr Battery", "Bluetooth 5.3", "Hi-Res Audio", "Foldable Design"],
        specifications: { "Driver Size": "40mm", "Frequency": "20Hz-40kHz", "Weight": "250g", "Charging": "USB-C" },
        gradient: "linear-gradient(135deg, #DBEAFE 0%, #BFDBFE 100%)",
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 2,
        name: "Minimalist Canvas Sneakers",
        category: "fashion",
        categoryLabel: "Fashion",
        price: 59.99,
        originalPrice: null,
        rating: 4.5,
        reviews: 189,
        description: "Clean, minimalist canvas sneakers perfect for everyday wear. Featuring a cushioned insole and durable rubber outsole for all-day comfort.",
        badge: "New",
        colors: ["#ffffff", "#2d3436", "#fab1a0"],
        sizes: ["38", "39", "40", "41", "42", "43", "44"],
        inStock: true,
        features: ["Cushioned Insole", "Durable Rubber Sole", "Breathable Canvas", "Classic Design"],
        specifications: { "Material": "Canvas", "Sole": "Rubber", "Closure": "Lace-up", "Care": "Spot Clean" },
        gradient: "linear-gradient(135deg, #FEF3C7 0%, #FDE68A 100%)",
        image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 3,
        name: "Smart Fitness Watch Ultra",
        category: "electronics",
        categoryLabel: "Electronics",
        price: 199.99,
        originalPrice: 249.99,
        rating: 4.7,
        reviews: 412,
        description: "Advanced fitness smartwatch with GPS, heart rate monitoring, SpO2 sensor, and 14-day battery life. Water-resistant to 50m.",
        badge: "Sale",
        colors: ["#2d3436", "#00b894", "#e17055"],
        sizes: null,
        inStock: true,
        features: ["GPS Tracking", "Heart Rate Monitor", "SpO2 Sensor", "14-Day Battery", "50m Water Resistant"],
        specifications: { "Display": "1.4\" AMOLED", "Battery": "420mAh", "Sensors": "HR, SpO2, Gyro", "OS": "Proprietary" },
        gradient: "linear-gradient(135deg, #1E3A5F 0%, #2563EB 50%, #60A5FA 100%)",
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 4,
        name: "Organic Cotton T-Shirt",
        category: "fashion",
        categoryLabel: "Fashion",
        price: 29.99,
        originalPrice: 39.99,
        rating: 4.3,
        reviews: 567,
        description: "Sustainably made organic cotton t-shirt. Soft, breathable, and perfect for layering. Pre-shrunk for a consistent fit wash after wash.",
        badge: "Sale",
        colors: ["#ffffff", "#2d3436", "#74b9ff", "#fab1a0", "#55efc4"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        inStock: true,
        features: ["100% Organic Cotton", "Pre-Shrunk", "Breathable", "Sustainable"],
        specifications: { "Material": "100% Organic Cotton", "Weight": "180gsm", "Fit": "Regular", "Care": "Machine Wash" },
        gradient: "linear-gradient(135deg, #D1FAE5 0%, #A7F3D0 100%)",
        image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 5,
        name: "Ceramic Pour-Over Coffee Set",
        category: "home",
        categoryLabel: "Home & Living",
        price: 45.99,
        originalPrice: null,
        rating: 4.9,
        reviews: 98,
        description: "Handcrafted ceramic pour-over coffee dripper set with matching mug and bamboo stand. Brew the perfect cup every morning.",
        badge: "New",
        colors: ["#ffffff", "#dfe6e9", "#ffeaa7"],
        sizes: null,
        inStock: true,
        features: ["Handcrafted", "Lead-Free Glaze", "Bamboo Stand", "Dishwasher Safe"],
        specifications: { "Material": "Ceramic + Bamboo", "Capacity": "360ml", "Filter": "Reusable Mesh", "Origin": "Japan" },
        gradient: "linear-gradient(135deg, #FEF3C7 0%, #FFEDD5 100%)",
        image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 6,
        name: "Vitamin C Brightening Serum",
        category: "beauty",
        categoryLabel: "Beauty",
        price: 34.99,
        originalPrice: 44.99,
        rating: 4.6,
        reviews: 321,
        description: "Powerful 20% Vitamin C serum with Hyaluronic Acid and Vitamin E. Brightens skin, reduces dark spots, and boosts collagen production.",
        badge: "Sale",
        colors: null,
        sizes: ["30ml", "50ml"],
        inStock: true,
        features: ["20% Vitamin C", "Hyaluronic Acid", "Paraben-Free", "Cruelty-Free"],
        specifications: { "Volume": "30ml", "Skin Type": "All Skin Types", "Usage": "Morning/Night", "Shelf Life": "12 months" },
        gradient: "linear-gradient(135deg, #FEF9C3 0%, #FDE68A 100%)",
        image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 7,
        name: "Ergonomic Office Chair",
        category: "home",
        categoryLabel: "Home & Living",
        price: 349.99,
        originalPrice: 449.99,
        rating: 4.8,
        reviews: 156,
        description: "Premium ergonomic office chair with lumbar support, adjustable armrests, breathable mesh back, and smooth-rolling casters.",
        badge: "Hot",
        colors: ["#2d3436", "#636e72", "#00b894"],
        sizes: null,
        inStock: true,
        features: ["Lumbar Support", "Adjustable Arms", "Mesh Back", "360° Swivel", "Height Adjustable"],
        specifications: { "Weight Capacity": "150kg", "Seat Height": "42-52cm", "Material": "Mesh + Nylon", "Warranty": "5 Years" },
        gradient: "linear-gradient(135deg, #E2E8F0 0%, #F1F5F9 100%)",
        image: "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 8,
        name: "Portable Bluetooth Speaker",
        category: "electronics",
        categoryLabel: "Electronics",
        price: 49.99,
        originalPrice: null,
        rating: 4.4,
        reviews: 289,
        description: "Compact, waterproof Bluetooth speaker with 360° sound, 12-hour battery, and built-in microphone for hands-free calls.",
        badge: null,
        colors: ["#2d3436", "#e17055", "#74b9ff", "#55efc4"],
        sizes: null,
        inStock: true,
        features: ["360° Sound", "IPX7 Waterproof", "12hr Battery", "Built-in Mic"],
        specifications: { "Output": "20W", "Bluetooth": "5.0", "Range": "15m", "Weight": "540g" },
        gradient: "linear-gradient(135deg, #DBEAFE 0%, #BFDBFE 100%)",
        image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 9,
        name: "Yoga Mat Premium 6mm",
        category: "sports",
        categoryLabel: "Sports",
        price: 39.99,
        originalPrice: null,
        rating: 4.7,
        reviews: 445,
        description: "Extra thick 6mm yoga mat with non-slip surface and alignment markings. Made from eco-friendly TPE material with carrying strap.",
        badge: "New",
        colors: ["#55efc4", "#74b9ff", "#fab1a0", "#a29bfe"],
        sizes: null,
        inStock: true,
        features: ["6mm Thick", "Non-Slip", "Alignment Lines", "Eco-Friendly TPE", "Carrying Strap"],
        specifications: { "Dimensions": "183x61cm", "Thickness": "6mm", "Material": "TPE", "Weight": "900g" },
        gradient: "linear-gradient(135deg, #10B981 0%, #6EE7B7 100%)",
        image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 10,
        name: "Leather Crossbody Bag",
        category: "fashion",
        categoryLabel: "Fashion",
        price: 79.99,
        originalPrice: 99.99,
        rating: 4.6,
        reviews: 178,
        description: "Genuine leather crossbody bag with adjustable strap, multiple compartments, and RFID-blocking pocket. Perfect for everyday carry.",
        badge: "Sale",
        colors: ["#795548", "#2d3436", "#d4a574"],
        sizes: null,
        inStock: true,
        features: ["Genuine Leather", "RFID Blocking", "Adjustable Strap", "Multiple Pockets"],
        specifications: { "Material": "Full Grain Leather", "Dimensions": "24x18x8cm", "Strap": "Adjustable", "Closure": "Magnetic Snap" },
        gradient: "linear-gradient(135deg, #FEF3C7 0%, #D4A574 100%)",
        image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 11,
        name: "Indoor Herb Garden Kit",
        category: "home",
        categoryLabel: "Home & Living",
        price: 54.99,
        originalPrice: null,
        rating: 4.5,
        reviews: 203,
        description: "Complete indoor herb garden kit with self-watering system, LED grow light, and seeds for basil, mint, and cilantro.",
        badge: "New",
        colors: null,
        sizes: null,
        inStock: true,
        features: ["Self-Watering", "LED Grow Light", "3 Herb Varieties", "BPA-Free Pods"],
        specifications: { "Dimensions": "38x12x36cm", "Light": "20W LED", "Capacity": "6 Pods", "Power": "AC Adapter" },
        gradient: "linear-gradient(135deg, #D1FAE5 0%, #A7F3D0 100%)",
        image: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 12,
        name: "Retinol Night Cream 2.5%",
        category: "beauty",
        categoryLabel: "Beauty",
        price: 28.99,
        originalPrice: 38.99,
        rating: 4.4,
        reviews: 267,
        description: "Advanced retinol night cream with shea butter and jojoba oil. Reduces fine lines, improves skin texture, and promotes cell renewal.",
        badge: "Sale",
        colors: null,
        sizes: ["30ml", "50ml"],
        inStock: true,
        features: ["2.5% Retinol", "Shea Butter", "Anti-Aging", "Paraben-Free"],
        specifications: { "Volume": "50ml", "Key Ingredient": "Retinol 2.5%", "Skin Type": "All Types", "Usage": "Nightly" },
        gradient: "linear-gradient(135deg, #EDE9FE 0%, #F5F3FF 100%)",
        image: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 13,
        name: "Stainless Steel Water Bottle",
        category: "sports",
        categoryLabel: "Sports",
        price: 24.99,
        originalPrice: null,
        rating: 4.8,
        reviews: 892,
        description: "Double-wall vacuum insulated water bottle. Keeps drinks cold 24hrs or hot 12hrs. BPA-free and leak-proof lid.",
        badge: "Hot",
        colors: ["#2d3436", "#74b9ff", "#fab1a0", "#55efc4", "#ffeaa7"],
        sizes: ["500ml", "750ml", "1L"],
        inStock: true,
        features: ["Vacuum Insulated", "24hr Cold/12hr Hot", "BPA-Free", "Leak-Proof"],
        specifications: { "Material": "18/8 Stainless Steel", "Capacity": "750ml", "Weight": "350g", "Insulation": "Double Wall" },
        gradient: "linear-gradient(135deg, #CFFAFE 0%, #A5F3FC 100%)",
        image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 14,
        name: "Wireless Charging Pad",
        category: "electronics",
        categoryLabel: "Electronics",
        price: 29.99,
        originalPrice: null,
        rating: 4.3,
        reviews: 345,
        description: "Slim wireless charging pad with 15W fast charging. Compatible with all Qi-enabled devices. LED indicator and anti-slip surface.",
        badge: null,
        colors: ["#2d3436", "#ffffff"],
        sizes: null,
        inStock: true,
        features: ["15W Fast Charge", "Qi Compatible", "Ultra Slim", "LED Indicator"],
        specifications: { "Output": "5W/7.5W/10W/15W", "Input": "USB-C", "Thickness": "7mm", "Diameter": "100mm" },
        gradient: "linear-gradient(135deg, #F1F5F9 0%, #F8FAFC 100%)",
        image: "https://images.unsplash.com/photo-1622445275463-afa2ab738c34?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 15,
        name: "Bestselling Novel Collection",
        category: "books",
        categoryLabel: "Books",
        price: 42.99,
        originalPrice: 59.99,
        rating: 4.9,
        reviews: 156,
        description: "Curated collection of 5 bestselling novels from top contemporary authors. Beautifully bound with a collectible slipcase.",
        badge: "Sale",
        colors: null,
        sizes: null,
        inStock: true,
        features: ["5 Novels", "Hardcover", "Collectible Slipcase", "Bookmark Ribbon"],
        specifications: { "Format": "Hardcover", "Pages": "~1500 total", "Language": "English", "Publisher": "Various" },
        gradient: "linear-gradient(135deg, #FEF3C7 0%, #FFEDD5 100%)",
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 16,
        name: "Aromatherapy Candle Set",
        category: "home",
        categoryLabel: "Home & Living",
        price: 32.99,
        originalPrice: null,
        rating: 4.7,
        reviews: 198,
        description: "Set of 4 hand-poured soy wax candles in lavender, eucalyptus, vanilla, and citrus. Each candle burns up to 45 hours.",
        badge: null,
        colors: null,
        sizes: null,
        inStock: true,
        features: ["Soy Wax", "4 Scents", "45hr Burn", "Cotton Wick", "Reusable Jars"],
        specifications: { "Weight": "200g each", "Burn Time": "45hrs each", "Material": "Soy Wax", "Wicks": "Cotton" },
        gradient: "linear-gradient(135deg, #FEF9C3 0%, #FDE68A 100%)",
        image: "https://images.unsplash.com/photo-1602607742427-6738e668ebe1?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 17,
        name: "Running Shoes CloudFlex",
        category: "sports",
        categoryLabel: "Sports",
        price: 119.99,
        originalPrice: 149.99,
        rating: 4.6,
        reviews: 334,
        description: "Lightweight running shoes with CloudFlex cushioning, breathable mesh upper, and responsive energy return. Perfect for road running.",
        badge: "Hot",
        colors: ["#2d3436", "#74b9ff", "#ff7675"],
        sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
        inStock: true,
        features: ["CloudFlex Cushioning", "Breathable Mesh", "Energy Return", "Lightweight"],
        specifications: { "Weight": "240g", "Drop": "8mm", "Upper": "Engineered Mesh", "Sole": "Rubber + CloudFlex" },
        gradient: "linear-gradient(135deg, #FFE4E6 0%, #FECDD3 100%)",
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 18,
        name: "Mechanical Keyboard RGB",
        category: "electronics",
        categoryLabel: "Electronics",
        price: 79.99,
        originalPrice: null,
        rating: 4.5,
        reviews: 267,
        description: "Compact mechanical keyboard with customizable RGB backlighting, hot-swappable switches, and aluminum frame.",
        badge: null,
        colors: ["#2d3436", "#ffffff"],
        sizes: null,
        inStock: true,
        features: ["Hot-Swappable", "RGB Backlit", "Aluminum Frame", "PBT Keycaps"],
        specifications: { "Layout": "75%", "Switch": "Gateron", "Connection": "USB-C / Bluetooth", "Keycaps": "PBT" },
        gradient: "linear-gradient(135deg, #E2E8F0 0%, #F1F5F9 100%)",
        image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 19,
        name: "Sunscreen SPF 50+ Glow",
        category: "beauty",
        categoryLabel: "Beauty",
        price: 22.99,
        originalPrice: null,
        rating: 4.8,
        reviews: 502,
        description: "Lightweight, non-greasy sunscreen with SPF 50+ and a dewy glow finish. Water-resistant for up to 80 minutes.",
        badge: "Hot",
        colors: null,
        sizes: ["50ml", "100ml"],
        inStock: true,
        features: ["SPF 50+", "Non-Greasy", "Water Resistant", "Dewy Finish", "Reef-Safe"],
        specifications: { "Volume": "50ml", "SPF": "50+", "PA": "PA++++", "Water Resistant": "80 min" },
        gradient: "linear-gradient(135deg, #FEF9C3 0%, #FCE7F3 100%)",
        image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 20,
        name: "Denim Jacket Classic Fit",
        category: "fashion",
        categoryLabel: "Fashion",
        price: 89.99,
        originalPrice: 109.99,
        rating: 4.4,
        reviews: 145,
        description: "Classic fit denim jacket in medium wash. Made from premium stretch denim with vintage-inspired brass buttons.",
        badge: null,
        colors: ["#5dade2", "#2d3436", "#d4e6f1"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        inStock: true,
        features: ["Premium Denim", "Stretch Fabric", "Brass Buttons", "Classic Fit"],
        specifications: { "Material": "98% Cotton, 2% Elastane", "Wash": "Medium", "Fit": "Classic", "Care": "Machine Wash Cold" },
        gradient: "linear-gradient(135deg, #DBEAFE 0%, #BFDBFE 100%)",
        image: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 21,
        name: "Science Fiction Epic Novel",
        category: "books",
        categoryLabel: "Books",
        price: 18.99,
        originalPrice: null,
        rating: 4.7,
        reviews: 289,
        description: "An award-winning science fiction epic that spans galaxies and generations. A must-read for fans of speculative fiction.",
        badge: "New",
        colors: null,
        sizes: null,
        inStock: true,
        features: ["Award-Winning", "580 Pages", "Paperback", "Signed Edition Available"],
        specifications: { "Format": "Paperback", "Pages": "580", "Language": "English", "ISBN": "978-000-000-0021" },
        gradient: "linear-gradient(135deg, #DBEAFE 0%, #BFDBFE 100%)",
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 22,
        name: "Resistance Bands Set Pro",
        category: "sports",
        categoryLabel: "Sports",
        price: 19.99,
        originalPrice: 29.99,
        rating: 4.5,
        reviews: 678,
        description: "Set of 5 latex resistance bands with varying tension levels. Includes door anchor, handles, ankle straps, and carry bag.",
        badge: "Sale",
        colors: null,
        sizes: null,
        inStock: true,
        features: ["5 Resistance Levels", "Latex-Free Option", "Complete Kit", "Carry Bag"],
        specifications: { "Levels": "10-50 lbs", "Material": "Natural Latex", "Includes": "5 Bands + Accessories", "Length": "48 inches" },
        gradient: "linear-gradient(135deg, #FCE7F3 0%, #FBCFE8 100%)",
        image: "https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 23,
        name: "Minimalist Desk Lamp",
        category: "home",
        categoryLabel: "Home & Living",
        price: 64.99,
        originalPrice: null,
        rating: 4.6,
        reviews: 123,
        description: "Sleek LED desk lamp with adjustable color temperature, brightness levels, and USB charging port. Touch-sensitive controls.",
        badge: "New",
        colors: ["#ffffff", "#2d3436", "#d4a574"],
        sizes: null,
        inStock: true,
        features: ["LED", "Adjustable Color Temp", "USB Charging", "Touch Controls", "Dimmable"],
        specifications: { "Wattage": "12W", "Color Temp": "2700K-6500K", "Port": "USB-A", "Height": "45cm" },
        gradient: "linear-gradient(135deg, #FEF3C7 0%, #FFEDD5 100%)",
        image: "https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=400&h=400&fit=crop&q=80"
    },
    {
        id: 24,
        name: "Face Mask Sheet Bundle",
        category: "beauty",
        categoryLabel: "Beauty",
        price: 15.99,
        originalPrice: 24.99,
        rating: 4.3,
        reviews: 445,
        description: "Bundle of 10 premium face mask sheets with hyaluronic acid, green tea, and collagen. Individually wrapped for freshness.",
        badge: "Sale",
        colors: null,
        sizes: null,
        inStock: true,
        features: ["10 Masks", "3 Formulas", "Individually Wrapped", "Vegan"],
        specifications: { "Count": "10 sheets", "Ingredients": "Hyaluronic, Green Tea, Collagen", "Skin Type": "All Types", "Origin": "Korea" },
        gradient: "linear-gradient(135deg, #ECFDF5 0%, #D1FAE5 100%)",
        image: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400&h=400&fit=crop&q=80"
    }
];

// Categories
const categories = [
    { slug: "electronics", name: "Electronics", icon: "ri-computer-line", count: 6, gradient: "linear-gradient(135deg, #2563EB 0%, #60A5FA 100%)", image: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=300&h=200&fit=crop&q=80" },
    { slug: "fashion", name: "Fashion", icon: "ri-t-shirt-line", count: 5, gradient: "linear-gradient(135deg, #F59E0B 0%, #FCD34D 100%)", image: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=300&h=200&fit=crop&q=80" },
    { slug: "home", name: "Home & Living", icon: "ri-home-smile-line", count: 5, gradient: "linear-gradient(135deg, #FEF3C7 0%, #FFEDD5 100%)", image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=200&fit=crop&q=80" },
    { slug: "beauty", name: "Beauty", icon: "ri-heart-pulse-line", count: 4, gradient: "linear-gradient(135deg, #F9A8D4 0%, #FBCFE8 100%)", image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=300&h=200&fit=crop&q=80" },
    { slug: "sports", name: "Sports", icon: "ri-basketball-line", count: 4, gradient: "linear-gradient(135deg, #10B981 0%, #6EE7B7 100%)", image: "https://images.unsplash.com/photo-1461896836934-bd45ba8fcf9b?w=300&h=200&fit=crop&q=80" },
    { slug: "books", name: "Books", icon: "ri-book-open-line", count: 2, gradient: "linear-gradient(135deg, #DBEAFE 0%, #EFF6FF 100%)", image: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=300&h=200&fit=crop&q=80" }
];

// Testimonials
const testimonials = [
    {
        id: 1,
        name: "Sarah Johnson",
        role: "Verified Buyer",
        avatar: "https://i.pravatar.cc/50?u=sarah-johnson",
        rating: 5,
        text: "Absolutely love the quality! The headphones are incredible, and the shipping was super fast. Will definitely shop here again!",
        product: "Wireless ANC Headphones Pro"
    },
    {
        id: 2,
        name: "Michael Chen",
        role: "Verified Buyer",
        avatar: "https://i.pravatar.cc/50?u=michael-chen",
        rating: 5,
        text: "The fitness watch exceeded my expectations. Accurate tracking, great battery life, and the design is stunning. Best purchase this year!",
        product: "Smart Fitness Watch Ultra"
    },
    {
        id: 3,
        name: "Emily Rodriguez",
        role: "Verified Buyer",
        avatar: "https://i.pravatar.cc/50?u=emily-rodriguez",
        rating: 4,
        text: "The pour-over coffee set is beautifully crafted. Makes my morning routine feel like a ritual. The ceramic quality is top-notch.",
        product: "Ceramic Pour-Over Coffee Set"
    },
    {
        id: 4,
        name: "David Kim",
        role: "Verified Buyer",
        avatar: "https://i.pravatar.cc/50?u=david-kim",
        rating: 5,
        text: "Great value for money! The organic cotton tees are so comfortable and hold up well after multiple washes. Ordered 5 more!",
        product: "Organic Cotton T-Shirt"
    }
];

// Export for use
if (typeof module !== 'undefined') {
    module.exports = { products, categories, testimonials };
}
